" First, turn off Vi compatibility mode
set nocompatible

" Plugin settings
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
call vundle#end()
filetype plugin indent on

" Color settings
set background=dark
set t_Co=256

" Code settings
syntax on
set number
set nowrap
set showmatch
set mouse=a
set list
set listchars=tab:->,trail:#,nbsp:.
highlight NonText ctermfg=245
highlight SpecialKey ctermfg=245
" Indent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smartindent
set expandtab

" Search settings
set showmatch
set incsearch
set hlsearch

" Status line settings
set laststatus=2
let g:airline_left_sep=''
let g:airline_right_sep=''

" File settings
set fileformat=unix
set fileformats=unix,dos,mac
" Unicode w/o BOM
set encoding=utf-8
set fileencodings=ucs-bom,utf-8
set nobomb
" Handling multibyte characters
if has('multi_byte')
    set fileencodings+=big5,cp950
    set fileencodings+=gbk,cp936,gb18030
    set fileencodings+=latin1
    set ambiwidth=double
else
    echoerr 'Sorry, this version of (g)vim was not compiled with multi_byte.'
    set fileencodings+=latin1
endif
" Do not backup
set nobackup
set noswapfile
