set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'

" Color schemes
Plugin 'chriskempson/base16-vim'

call vundle#end()
filetype plugin indent on

" Status bar
"set statusline=%<\ %f\ %y[%{&ff}][%{strlen(&fenc)?&fenc:'none'}]%m%r%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ %)

" Airline
set laststatus=2
let g:airline_left_sep=''
let g:airline_right_sep=''

" Encoding
if has('multi_byte')
  set fileencodings=utf-8,big5
if v:lang =~ '^zh_TW'
  set encoding=big5
  set termencoding=big5
  set fileencoding=big5
endif
if v:lang =~ 'utf8$' || v:lang =~ 'UTF-8$'
  set encoding=utf-8
  set termencoding=utf-8
  set fileencoding=utf-8
endif
else
  echoerr 'Sorry, this version of (g)vim was not compiled with multi_byte.'
endif
set nobomb

" Indent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2

" Search
set showmatch
set incsearch
set hlsearch
set ignorecase

" Color
syntax on
set number
set background=dark
set t_Co=256
