# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

[ -f /etc/bash_completion ] && source /etc/bash_completion
[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash

[ -d $HOME/local/bin ] && PATH=$HOME/local/bin:$PATH
[ -d /usr/local/bin ] && PATH=/usr/local/bin:$PATH
