alias ..='cd ..'

if [[ $OSTYPE =~ ^darwin ]]; then
  alias ls='ls -G'
else
  alias ls='ls --color=auto'
fi

alias ll='ls -Fhl'
alias la='ll -A'
alias rm='rm -i'
alias less='less -rXF'

alias e64=encode64
alias d64=decode64

alias reload=reload_profile
